name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.0.2
  delightful_toast: ^1.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.1.1
  flutter_zoom_drawer: ^3.2.0
  image_picker: ^1.1.2
  path: ^1.9.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icon/
  - assets/images/

